image: registry-gitlab.pasteur.fr/dsi-tools/docker-images/docker:latest

services:
    - registry-gitlab.pasteur.fr/dsi-tools/docker-images/docker:dind
stages:
    - build

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" registry-gitlab.pasteur.fr
    - export  MY_TIME=`date +"%F-%H%M"`
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME" -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" -t "$CI_REGISTRY_IMAGE:latest" -t "$CI_REGISTRY_IMAGE:$MY_TIME" .
    - docker push "$CI_REGISTRY_IMAGE"
